on:
  push:
    branches:
      - master

name: Build and Release Apps
jobs:
  build:
    name: Build Windows Release
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: stable
      - name: Add Flutter to path	
        run: echo "::add-path::$GITHUB_WORKSPACE/flutter/bin"	
      - run: flutter config --enable-windows-desktop
      - run: flutter build windows
