on:
  push:
    branches:
      - master

name: Build and Release Apps
jobs:
  build:
    name: Build Windows Release
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: beta
      - run: flutter config --enable-windows-desktop
      - run: flutter build windows
